### PR TITLE
adding docker file

### PR DESCRIPTION
**Pull request by ynachiket**
docker build . 
docker run [hash/tag from build step] nodejs index.js

(We can add an entry point to the Docker file which will allow us to just do a docker run. But this seems like an example and so I kept it simple).

### CODE REVIEW

**Comment by bravelittlescientist** [comment]
Hm, when I run this from your branch, I see the following. 

ending build context to Docker daemon
2014/08/26 11:45:49 Post http:///var/run/docker.sock/build?rm=1&t=: dial unix /var/run/docker.sock: no such file or directory

Searching around, seems like DOCKER_HOST is not set. Is anything else required to make this run?

**Comment by ynachiket** [comment]
you will need to export docker host. i would suggest putting it in your bashrc

**Comment by bravelittlescientist** [comment]
Putting these instructions here, for future reference.

boot2docker delete
boot2docker download
boot2docker init
boot2docker up
export DOCKER_HOST=tcp://192.168.59.103:2375
docker images

**Comment by bravelittlescientist** [comment]
+1

**Pull request merged**
